# Generated by Django 4.2.16 on 2024-09-15 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=datetime.datetime(2024, 9, 15, 22, 44, 7, 270386, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
